"""initial schema

Revision ID: a4734d520a91
Revises: 
Create Date: 2026-08-07 21:04:15.111749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4734d520a91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('province_state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('google_profile_url', sa.Text(), nullable=True),
    sa.Column('google_review_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED')", name='ck_merchants_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('merchants_google_place_id_idx', 'merchants', ['google_place_id'], unique=True, postgresql_where=sa.text('google_place_id IS NOT NULL'))
    op.create_table('merchant_review_context',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('menu_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selling_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('smart_review_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('disabled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('first_opened_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_opened_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('generation_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('suggestion_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('selected_suggestion_id', sa.UUID(), nullable=True),
    sa.Column('google_redirected_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE', 'COMPLETED', 'DISABLED')", name='ck_sessions_status'),
    sa.CheckConstraint('length(token) > 0', name='ck_sessions_token_not_blank'),
    sa.CheckConstraint('open_count >= 0 AND generation_count >= 0 AND suggestion_count >= 0', name='ck_sessions_counts_non_negative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    # fk_session_selected_suggestion is created after smart_review_suggestions
    # exists — see below. Left inline with use_alter=True, op.create_table
    # silently discards it, leaving the column with no integrity at all.
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('smart_review_sessions_expiry_idx', 'smart_review_sessions', ['expires_at'], unique=False)
    op.create_index('smart_review_sessions_ip_created_idx', 'smart_review_sessions', ['created_ip_hash', 'created_at'], unique=False)
    op.create_index('smart_review_sessions_merchant_idx', 'smart_review_sessions', ['merchant_id'], unique=False)
    op.create_index('smart_review_sessions_selected_idx', 'smart_review_sessions', ['selected_suggestion_id'], unique=False)
    op.create_table('smart_review_suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('generation_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=60), nullable=True),
    sa.Column('model_provider', sa.String(length=60), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=30), nullable=True),
    sa.Column('selected_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('generation_number >= 1', name='ck_suggestion_generation_number'),
    sa.CheckConstraint('length(btrim(text)) > 0', name='ck_suggestion_text_not_blank'),
    sa.CheckConstraint('position >= 1', name='ck_suggestion_position'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['smart_review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'session_id', name='uq_suggestion_id_session'),
    sa.UniqueConstraint('session_id', 'generation_number', 'position', name='uq_suggestion_session_generation_position')
    )
    op.create_index('smart_review_suggestions_session_generation_idx', 'smart_review_suggestions', ['session_id', 'generation_number'], unique=False)
    # Composite on purpose: referencing (id, session_id) means the database
    # itself rejects a session whose selected suggestion belongs to a different
    # session. The column list on SET NULL requires Postgres 15+; a bare SET
    # NULL would try to null this session's own primary key and fail.
    op.create_foreign_key(
        'fk_session_selected_suggestion',
        'smart_review_sessions',
        'smart_review_suggestions',
        ['selected_suggestion_id', 'id'],
        ['id', 'session_id'],
        ondelete='SET NULL (selected_suggestion_id)',
    )
    op.create_table('smart_review_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_session_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("event_type IN ('SESSION_CREATED', 'SESSION_OPENED', 'SUGGESTIONS_GENERATED', 'SUGGESTION_SELECTED', 'SESSION_COMPLETED', 'GENERATION_FAILED')", name='ck_events_event_type'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['smart_review_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['smart_review_suggestions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('smart_review_events_merchant_time_idx', 'smart_review_events', ['merchant_id', 'created_at'], unique=False)
    op.create_index('smart_review_events_session_time_idx', 'smart_review_events', ['session_id', 'created_at'], unique=False)
    op.create_index('smart_review_events_type_time_idx', 'smart_review_events', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Dropped first: smart_review_suggestions cannot be dropped while this
    # constraint still references it.
    op.drop_constraint('fk_session_selected_suggestion', 'smart_review_sessions', type_='foreignkey')
    op.drop_index('smart_review_events_type_time_idx', table_name='smart_review_events')
    op.drop_index('smart_review_events_session_time_idx', table_name='smart_review_events')
    op.drop_index('smart_review_events_merchant_time_idx', table_name='smart_review_events')
    op.drop_table('smart_review_events')
    op.drop_index('smart_review_suggestions_session_generation_idx', table_name='smart_review_suggestions')
    op.drop_table('smart_review_suggestions')
    op.drop_index('smart_review_sessions_selected_idx', table_name='smart_review_sessions')
    op.drop_index('smart_review_sessions_merchant_idx', table_name='smart_review_sessions')
    op.drop_index('smart_review_sessions_ip_created_idx', table_name='smart_review_sessions')
    op.drop_index('smart_review_sessions_expiry_idx', table_name='smart_review_sessions')
    op.drop_table('smart_review_sessions')
    op.drop_table('merchant_review_context')
    op.drop_index('merchants_google_place_id_idx', table_name='merchants', postgresql_where=sa.text('google_place_id IS NOT NULL'))
    op.drop_table('merchants')
    # ### end Alembic commands ###
