"""generation attempts ceiling

Revision ID: e588b5708369
Revises: a4734d520a91
Create Date: 2026-08-07 22:31:52.861588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e588b5708369'
down_revision: Union[str, Sequence[str], None] = 'a4734d520a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('smart_review_sessions', sa.Column('generation_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # Autogenerate does not detect CHECK constraint changes, so the new counter
    # has to be folded into the non-negative guard by hand — otherwise a buggy
    # decrement on this column would go unnoticed, which is exactly the failure
    # the guard exists to catch.
    op.drop_constraint('ck_sessions_counts_non_negative', 'smart_review_sessions', type_='check')
    op.create_check_constraint(
        'ck_sessions_counts_non_negative',
        'smart_review_sessions',
        'open_count >= 0 AND generation_count >= 0 AND suggestion_count >= 0 '
        'AND generation_attempts >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_sessions_counts_non_negative', 'smart_review_sessions', type_='check')
    op.create_check_constraint(
        'ck_sessions_counts_non_negative',
        'smart_review_sessions',
        'open_count >= 0 AND generation_count >= 0 AND suggestion_count >= 0',
    )
    op.drop_column('smart_review_sessions', 'generation_attempts')
    # ### end Alembic commands ###
